name: flutterfly
description: A collection of common widgets, validators, extensions, utilities, as well as some other stuffs that are currently non-existent.
version: 0.2.0+7
homepage: https://github.com/wowsomeco/flutterfly

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
