name: flutterfly
description: A collection of Lightweight Material UI components that will save your development costs drastically.
version: 0.1.0+10
homepage: https://github.com/wowsomeco/flutterfly

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
